services:
  postgres:
    image: postgres:16
    container_name: custom_merch_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # DB user
      POSTGRES_PASSWORD: postgres # DB password
      POSTGRES_DB: postgres # DB name
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: custom_merch_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # login email for pgAdmin UI
      PGADMIN_DEFAULT_PASSWORD: password # login password for pgAdmin UI
    ports:
      - '5050:80' # pgAdmin will be available at http://localhost:5050
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: merch_app
  #   restart: always
  #   ports:
  #     - '5000:3000'
  #   environment:
  #     - NODE_ENV=production
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=postgres
  #   depends_on:
  #     - postgres

  app:
    image: node:20-alpine
    container_name: merch_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '5000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    command: sh -c "npm install && npm run dev"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
